"""add user.is_bot and bot_profile table

Revision ID: ba3a85c3b675
Revises: c4d5e6f7a8b9
Create Date: 2026-08-29 21:07:14.232200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ba3a85c3b675'
down_revision: Union[str, Sequence[str], None] = 'c4d5e6f7a8b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('template', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('market_scope', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_trade_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bot_profile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bot_profile_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_bot_profile_user_id'), ['user_id'], unique=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        # server_default：生产 user 表已有行，NOT NULL 必须带默认回填；与模型 default=False 一致
        batch_op.add_column(sa.Column('is_bot', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.create_index(batch_op.f('ix_user_is_bot'), ['is_bot'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_is_bot'))
        batch_op.drop_column('is_bot')

    with op.batch_alter_table('bot_profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bot_profile_user_id'))
        batch_op.drop_index(batch_op.f('ix_bot_profile_status'))

    op.drop_table('bot_profile')
    # ### end Alembic commands ###
