"""add administrator redemption fulfillment

Revision ID: 0d0ac23efa85
Revises: ba3a85c3b675
Create Date: 2026-09-26 23:01:43.863735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d0ac23efa85'
down_revision: Union[str, Sequence[str], None] = 'ba3a85c3b675'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('redemption_code', schema=None) as batch_op:
        batch_op.add_column(sa.Column('redeemed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('redeemed_by_admin_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('redemption_note', sa.String(length=500), nullable=False, server_default=''))
        batch_op.create_index(batch_op.f('ix_redemption_code_redeemed_at'), ['redeemed_at'], unique=False)
        batch_op.create_foreign_key('fk_redemption_code_redeemed_by_admin_id_user', 'user', ['redeemed_by_admin_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('redemption_code', schema=None) as batch_op:
        batch_op.drop_constraint('fk_redemption_code_redeemed_by_admin_id_user', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_redemption_code_redeemed_at'))
        batch_op.drop_column('redemption_note')
        batch_op.drop_column('redeemed_by_admin_id')
        batch_op.drop_column('redeemed_at')

    # ### end Alembic commands ###
