"""add ledger_entry table

Revision ID: b2cd21122925
Revises: e1f8319139a1
Create Date: 2026-05-30 18:35:30.457908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = 'b2cd21122925'
down_revision: Union[str, Sequence[str], None] = 'e1f8319139a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledger_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entry_type', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('cash_delta', sa.Numeric(precision=16, scale=6), nullable=False),
    sa.Column('debt_delta', sa.Numeric(precision=16, scale=6), nullable=False),
    sa.Column('cash_after', sa.Numeric(precision=16, scale=6), nullable=False),
    sa.Column('debt_after', sa.Numeric(precision=16, scale=6), nullable=False),
    sa.Column('debt_last_accrued_at_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('daily_rate_at_event', sa.Numeric(precision=16, scale=8), nullable=True),
    sa.Column('operator_user_id', sa.Integer(), nullable=True),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['operator_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ledger_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ledger_entry_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_ledger_entry_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_entry_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ledger_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ledger_entry_user_id'))
        batch_op.drop_index('ix_ledger_entry_user_created')
        batch_op.drop_index(batch_op.f('ix_ledger_entry_created_at'))

    op.drop_table('ledger_entry')
    # ### end Alembic commands ###
