"""add outcome_candle table

Revision ID: dd985fe0c723
Revises: 4902aeac33ce
Create Date: 2026-05-17 02:43:44.601543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dd985fe0c723'
down_revision: Union[str, Sequence[str], None] = '4902aeac33ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outcome_candle',
    sa.Column('outcome_id', sa.Integer(), nullable=False),
    sa.Column('interval', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('bucket_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open_price', sa.Numeric(precision=16, scale=8), nullable=False),
    sa.Column('high_price', sa.Numeric(precision=16, scale=8), nullable=False),
    sa.Column('low_price', sa.Numeric(precision=16, scale=8), nullable=False),
    sa.Column('close_price', sa.Numeric(precision=16, scale=8), nullable=False),
    sa.Column('volume_shares', sa.Numeric(precision=16, scale=6), nullable=False),
    sa.Column('n_trades', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("interval IN ('10s', '1m', '15m', '1h')", name='ck_candle_interval_supported'),
    sa.CheckConstraint('high_price >= low_price', name='ck_candle_h_ge_l'),
    sa.CheckConstraint('n_trades >= 0', name='ck_candle_n_non_negative'),
    sa.CheckConstraint('volume_shares >= 0', name='ck_candle_volume_non_negative'),
    sa.ForeignKeyConstraint(['outcome_id'], ['outcome.id'], ),
    sa.PrimaryKeyConstraint('outcome_id', 'interval', 'bucket_start')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outcome_candle')
    # ### end Alembic commands ###
