"""add danmuku_exchange table

Revision ID: 4902aeac33ce
Revises: fc71e69823e7
Create Date: 2026-05-15 14:20:06.857954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4902aeac33ce'
down_revision: Union[str, Sequence[str], None] = 'fc71e69823e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('danmuku_exchange',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('qq_user_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('room_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('yuan', sa.Numeric(precision=16, scale=6), nullable=False),
    sa.Column('huo', sa.Numeric(precision=16, scale=6), nullable=False),
    sa.Column('amount', sa.Numeric(precision=16, scale=6), nullable=False),
    sa.Column('code_string', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_danmuku_exchange_timestamp'), 'danmuku_exchange', ['timestamp'], unique=False)
    op.create_index(op.f('ix_danmuku_exchange_user_id'), 'danmuku_exchange', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_danmuku_exchange_user_id'), table_name='danmuku_exchange')
    op.drop_index(op.f('ix_danmuku_exchange_timestamp'), table_name='danmuku_exchange')
    op.drop_table('danmuku_exchange')
    # ### end Alembic commands ###
