"""add outcome_candle table

Revision ID: dd985fe0c723
Revises: 4902aeac33ce
Create Date: 2026-05-17 02:43:44.601543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dd985fe0c723'
down_revision: Union[str, Sequence[str], None] = '4902aeac33ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema. 幂等：前次 fail 留下半成品也能恢复。"""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    table_existed = "outcome_candle" in inspector.get_table_names()

    if not table_existed:
        op.create_table('outcome_candle',
        sa.Column('outcome_id', sa.Integer(), nullable=False),
        sa.Column('interval', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
        sa.Column('bucket_start', sa.DateTime(timezone=True), nullable=False),
        sa.Column('open_price', sa.Numeric(precision=16, scale=8), nullable=False),
        sa.Column('high_price', sa.Numeric(precision=16, scale=8), nullable=False),
        sa.Column('low_price', sa.Numeric(precision=16, scale=8), nullable=False),
        sa.Column('close_price', sa.Numeric(precision=16, scale=8), nullable=False),
        sa.Column('volume_shares', sa.Numeric(precision=16, scale=6), nullable=False),
        sa.Column('n_trades', sa.Integer(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("interval IN ('10s', '1m', '15m', '1h')", name='ck_candle_interval_supported'),
        sa.CheckConstraint('high_price >= low_price', name='ck_candle_h_ge_l'),
        sa.CheckConstraint('n_trades >= 0', name='ck_candle_n_non_negative'),
        sa.CheckConstraint('volume_shares >= 0', name='ck_candle_volume_non_negative'),
        sa.ForeignKeyConstraint(['outcome_id'], ['outcome.id'], ),
        sa.PrimaryKeyConstraint('outcome_id', 'interval', 'bucket_start')
        )
    else:
        # 前次 migration fail 留下的表 + 可能的 partial INSERT（alembic_version
        # 未推进所以重跑到这里）。清空让回填从干净状态重建，避免 ON CONFLICT
        # DO UPDATE 累加污染 volume/n_trades。
        print("[migration] outcome_candle 表已存在（前次 fail 留下），DELETE 清空准备重建")
        bind.execute(sa.text("DELETE FROM outcome_candle"))

    # ── 回填历史 Transaction → outcome_candle（spec § 6） ──
    # 必须用 op.get_bind() 拿 alembic 当前 connection；不能新建 sync_engine。
    # 原因：Postgres DDL（CREATE TABLE）在 alembic 默认 transactional_ddl 模式
    # 下也可能 autocommit（取决于 driver/版本）。独立 engine 开新 connection 在
    # CREATE TABLE 后看不到表 → INSERT 时 relation does not exist。
    # 用 op.get_bind() 共享同一 connection 既避免可见性问题、也保证回填跟
    # CREATE TABLE 在同一逻辑事务里 commit/rollback。
    #
    # 代价：回填必须跟 CREATE TABLE 在同一个 alembic 事务里跑完，"按 market
    # 分批提交"无法实现。对当前规模（百~千笔 trade）一个大事务足够快。
    _backfill_in_alembic_tx(bind)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outcome_candle')
    # ### end Alembic commands ###


def _backfill_in_alembic_tx(connection) -> None:
    """在 alembic 当前 connection / 事务里跑回填。

    `connection` 是 op.get_bind() 拿到的；它跟 CREATE TABLE 在同一事务，能看
    到新建的 outcome_candle。回填的 INSERT 也走这条 connection，回填结果跟
    CREATE TABLE 一起被 alembic 的外层 tx COMMIT（成功）或 ROLLBACK（失败）。

    `Session(bind=connection)` 跟 sessionmaker(bind=engine) 的区别：前者复用
    传入的 connection（已有 tx context），不开新 tx；session 内调 commit/flush
    都受外层 alembic tx 管控。回填失败时无需手动 rollback——alembic 会一起回滚。
    """
    from sqlalchemy.orm import Session
    from app.models.base import Market

    session = Session(bind=connection)
    try:
        market_ids = [r[0] for r in session.execute(sa.select(Market.id).order_by(Market.id)).all()]
        print(f"[migration] 回填 {len(market_ids)} 个 market 的 candle 数据...")
        for mid in market_ids:
            _backfill_one_market_sync(session, mid)
            session.flush()  # 让本 market 数据进 DB，但不 commit（alembic 管 commit）
            print(f"[migration]   market {mid} done")
    finally:
        session.close()


def _backfill_one_market_sync(s, market_id: int) -> None:
    """同步版的 backfill_one_market（不依赖 AsyncSession）。
    逻辑跟 app/services/candle_writer.py:backfill_one_market 完全一致。
    """
    from decimal import Decimal
    from app.models.base import Market, Outcome, Transaction, TransactionType, OutcomeCandle
    from app.services.candle_writer import compute_candle_rows
    from sqlalchemy.dialects.postgresql import insert as pg_insert
    from sqlalchemy.dialects.sqlite import insert as sqlite_insert
    from sqlalchemy import func

    market = s.get(Market, market_id)
    if market is None:
        return
    outcomes = s.execute(
        sa.select(Outcome).where(Outcome.market_id == market_id).order_by(Outcome.id)
    ).scalars().all()
    if not outcomes:
        return
    outcome_ids = [o.id for o in outcomes]

    txs = s.execute(
        sa.select(Transaction)
        .where(
            Transaction.outcome_id.in_(outcome_ids),
            Transaction.type.in_([TransactionType.BUY, TransactionType.SELL]),
        )
        .order_by(Transaction.timestamp.asc())
    ).scalars().all()

    dialect = s.bind.dialect.name
    insert_fn = pg_insert if dialect == "postgresql" else sqlite_insert
    greatest = func.greatest if dialect == "postgresql" else func.max
    least = func.least if dialect == "postgresql" else func.min

    for tx in txs:
        if tx.market_prices_post and len(tx.market_prices_post) == len(outcome_ids):
            new_prices = [float(p) for p in tx.market_prices_post]
        else:
            new_prices = [
                float(tx.post_market_price) if oid == tx.outcome_id
                else 1.0 / len(outcome_ids) for oid in outcome_ids
            ]
        rows = compute_candle_rows(
            traded_outcome_id=tx.outcome_id,
            outcome_ids=outcome_ids,
            new_prices=new_prices,
            traded_shares=tx.shares,
            ts=tx.timestamp,
        )
        if not rows:
            continue
        stmt = insert_fn(OutcomeCandle).values(rows)
        stmt = stmt.on_conflict_do_update(
            index_elements=["outcome_id", "interval", "bucket_start"],
            set_={
                "high_price":    greatest(OutcomeCandle.high_price, stmt.excluded.high_price),
                "low_price":     least(OutcomeCandle.low_price, stmt.excluded.low_price),
                "close_price":   stmt.excluded.close_price,
                "volume_shares": OutcomeCandle.volume_shares + stmt.excluded.volume_shares,
                "n_trades":      OutcomeCandle.n_trades + stmt.excluded.n_trades,
                "updated_at":    func.now(),
            },
        )
        s.execute(stmt)
