"""add outcome_candle table

Revision ID: dd985fe0c723
Revises: 4902aeac33ce
Create Date: 2026-05-17 02:43:44.601543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dd985fe0c723'
down_revision: Union[str, Sequence[str], None] = '4902aeac33ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outcome_candle',
    sa.Column('outcome_id', sa.Integer(), nullable=False),
    sa.Column('interval', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('bucket_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open_price', sa.Numeric(precision=16, scale=8), nullable=False),
    sa.Column('high_price', sa.Numeric(precision=16, scale=8), nullable=False),
    sa.Column('low_price', sa.Numeric(precision=16, scale=8), nullable=False),
    sa.Column('close_price', sa.Numeric(precision=16, scale=8), nullable=False),
    sa.Column('volume_shares', sa.Numeric(precision=16, scale=6), nullable=False),
    sa.Column('n_trades', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("interval IN ('10s', '1m', '15m', '1h')", name='ck_candle_interval_supported'),
    sa.CheckConstraint('high_price >= low_price', name='ck_candle_h_ge_l'),
    sa.CheckConstraint('n_trades >= 0', name='ck_candle_n_non_negative'),
    sa.CheckConstraint('volume_shares >= 0', name='ck_candle_volume_non_negative'),
    sa.ForeignKeyConstraint(['outcome_id'], ['outcome.id'], ),
    sa.PrimaryKeyConstraint('outcome_id', 'interval', 'bucket_start')
    )
    # ### end Alembic commands ###

    # ── 回填历史 Transaction → outcome_candle（spec § 6） ──
    # 用独立 sync engine 跑回填；按 market 分批提交，避免单巨型事务长锁
    # Transaction 表。URL 走 settings.build_db_url() 跟 alembic env.py 同步，
    # 再把异步驱动换成 sync 对应驱动。
    from sqlalchemy import create_engine
    from app.core.config import settings

    sync_url = settings.build_db_url()
    sync_url = sync_url.replace("postgresql+asyncpg", "postgresql+psycopg2")
    sync_url = sync_url.replace("sqlite+aiosqlite", "sqlite")
    sync_url = sync_url.replace("mysql+asyncmy", "mysql+pymysql")
    sync_engine = create_engine(sync_url)
    try:
        _backfill_sync(sync_engine)
    finally:
        sync_engine.dispose()


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outcome_candle')
    # ### end Alembic commands ###


def _backfill_sync(sync_engine) -> None:
    """同步版本的回填：在 alembic upgrade 上下文中调用。
    按 market 分批提交，避免单巨型事务长锁。
    """
    from sqlalchemy.orm import sessionmaker
    from app.models.base import Market

    SessionLocal = sessionmaker(bind=sync_engine)
    with SessionLocal() as s:
        market_ids = [r[0] for r in s.execute(sa.select(Market.id).order_by(Market.id)).all()]

    print(f"[migration] 回填 {len(market_ids)} 个 market 的 candle 数据...")
    for mid in market_ids:
        # 每 market 一个独立 session/事务，避免长锁
        with SessionLocal() as s:
            _backfill_one_market_sync(s, mid)
            s.commit()
        print(f"[migration]   market {mid} done")


def _backfill_one_market_sync(s, market_id: int) -> None:
    """同步版的 backfill_one_market（不依赖 AsyncSession）。
    逻辑跟 app/services/candle_writer.py:backfill_one_market 完全一致。
    """
    from decimal import Decimal
    from app.models.base import Market, Outcome, Transaction, TransactionType, OutcomeCandle
    from app.services.candle_writer import compute_candle_rows
    from sqlalchemy.dialects.postgresql import insert as pg_insert
    from sqlalchemy.dialects.sqlite import insert as sqlite_insert
    from sqlalchemy import func

    market = s.get(Market, market_id)
    if market is None:
        return
    outcomes = s.execute(
        sa.select(Outcome).where(Outcome.market_id == market_id).order_by(Outcome.id)
    ).scalars().all()
    if not outcomes:
        return
    outcome_ids = [o.id for o in outcomes]

    txs = s.execute(
        sa.select(Transaction)
        .where(
            Transaction.outcome_id.in_(outcome_ids),
            Transaction.type.in_([TransactionType.BUY, TransactionType.SELL]),
        )
        .order_by(Transaction.timestamp.asc())
    ).scalars().all()

    dialect = s.bind.dialect.name
    insert_fn = pg_insert if dialect == "postgresql" else sqlite_insert
    greatest = func.greatest if dialect == "postgresql" else func.max
    least = func.least if dialect == "postgresql" else func.min

    for tx in txs:
        if tx.market_prices_post and len(tx.market_prices_post) == len(outcome_ids):
            new_prices = [float(p) for p in tx.market_prices_post]
        else:
            new_prices = [
                float(tx.post_market_price) if oid == tx.outcome_id
                else 1.0 / len(outcome_ids) for oid in outcome_ids
            ]
        rows = compute_candle_rows(
            traded_outcome_id=tx.outcome_id,
            outcome_ids=outcome_ids,
            new_prices=new_prices,
            traded_shares=tx.shares,
            ts=tx.timestamp,
        )
        if not rows:
            continue
        stmt = insert_fn(OutcomeCandle).values(rows)
        stmt = stmt.on_conflict_do_update(
            index_elements=["outcome_id", "interval", "bucket_start"],
            set_={
                "high_price":    greatest(OutcomeCandle.high_price, stmt.excluded.high_price),
                "low_price":     least(OutcomeCandle.low_price, stmt.excluded.low_price),
                "close_price":   stmt.excluded.close_price,
                "volume_shares": OutcomeCandle.volume_shares + stmt.excluded.volume_shares,
                "n_trades":      OutcomeCandle.n_trades + stmt.excluded.n_trades,
                "updated_at":    func.now(),
            },
        )
        s.execute(stmt)
